version: 0.0
os: linux
files:
  # unzip the build artifact in ~/app
  - source: /
    destination: /var/www/html
permissions:
  # change permissions from root to ec2-user
  - object: /home/ec2-user/app
    pattern: "**"
    owner: ec2-user
    group: ec2-user
